index:
    path: /index
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact


login:
    path: /
    controller: App\Controller\DefaultController::login

user:
    path: /user
    controller: App\Controller\UserController::user 

animal:
    path: /animal
    controller: App\Controller\DefaultController::animal

facture:
    path: /facture
    controller: App\Controller\DefaultController::facture

error:
    path: /error
    controller: App\Controller\DefaultController::error

